### PR TITLE
Generate plain text versions of wiki articles, with links in footnotes

### PR DESCRIPTION
**Pull request by audiodude**
This PR modifies the makefile of the wiki to generate .txt versions of every page. The idea here is that these versions can be used from the command line and displayed to user in a CLI version of the wiki.

A lua filter has been added in order to take links [1] and put them at the bottom of the file, like that last one. This is because by default when pandoc converts to plain text, the link URL is completely lost.

[1] https://github.com/tildeclub/site/compare/plain-text-wiki?expand=1#diff-3799ed43dc8c11e6b07d510c0ee9f4b5

### CODE REVIEW

**Comment by audiodude** [comment]
Of course as soon as I finished this, I realized that maybe the CLI version of the wiki is just a script that opens the wiki URL in lynx, because the wiki pages look pretty good in lynx.

**Comment by deepend-tildeclub** [comment]
Does links in footnote mean the txt files would have a link at the bottom of the html pages?  If so that is not currently working :)

**Comment by audiodude** [comment]
No it's only for the .txt versions of the page. In HTML the links are just links.

**Comment by deepend-tildeclub** [comment]
Oh ok.. sounds good :)  Then it is all good.   Pulled and generated the new files :)   Thanks @audiodude

**Pull request merged**
